#!/usr/bin/env python3
"""Stamp a firmware build with its git revision.

Build-tool agnostic: the logic is a plain function plus a CLI. PlatformIO
integration is the small shim at the bottom, and any other build system can
run the same command before compiling:

    python scripts/build_info.py                      # writes include/build_info.hh
    python scripts/build_info.py -o build/version.hh  # anywhere else

The generated header defines:

    BUILD_GIT_SHA       short commit hash, e.g. "1387909f0909"
    BUILD_GIT_DIRTY     1 if tracked files have uncommitted changes
    BUILD_VERSION       `git describe --tags --always --dirty`, e.g.
                        "v1.2-3-g1387909-dirty" (or just the hash with no tags)

The file is only rewritten when its content changes, so an unchanged revision
does not trigger a recompile. It is generated, git-ignored and must not be
edited or committed. Outside a git checkout every value falls back to
"unknown" so a source tarball still builds.
"""
from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys

HEADER_NAME = "build_info.hh"


def git(repo_dir: pathlib.Path, *args: str) -> str | None:
    """Run a git command in `repo_dir`; None if git is missing or the command fails."""
    try:
        return subprocess.check_output(
            ["git", *args], cwd=repo_dir, stderr=subprocess.DEVNULL, text=True
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def describe(repo_dir: pathlib.Path) -> dict[str, str | bool]:
    """Collect the revision facts for `repo_dir`."""
    sha = git(repo_dir, "rev-parse", "--short=12", "HEAD") or "unknown"
    dirty = bool(git(repo_dir, "status", "--porcelain", "--untracked-files=no"))
    version = git(repo_dir, "describe", "--tags", "--always", "--dirty") or sha
    return {"sha": sha, "dirty": dirty, "version": version}


def render(info: dict[str, str | bool]) -> str:
    """Header text for a set of revision facts."""
    return (
        "// Generated by scripts/build_info.py before each firmware build.\n"
        "// Do not edit, do not commit (see .gitignore).\n"
        "#pragma once\n"
        f'#define BUILD_GIT_SHA "{info["sha"]}"\n'
        f"#define BUILD_GIT_DIRTY {1 if info['dirty'] else 0}\n"
        f'#define BUILD_VERSION "{info["version"]}"\n'
    )


def write_build_info(repo_dir: pathlib.Path, output: pathlib.Path) -> bool:
    """Write the header for `repo_dir` to `output` if it changed.

    Returns True when the file was (re)written, False when it was already current.
    """
    content = render(describe(repo_dir))
    if output.exists() and output.read_text() == content:
        return False
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content)
    return True


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    root = pathlib.Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description="Generate build_info.hh from the git revision.")
    parser.add_argument("-o", "--output", type=pathlib.Path, default=root / "include" / HEADER_NAME,
                        help=f"header to write (default: include/{HEADER_NAME})")
    parser.add_argument("--repo", type=pathlib.Path, default=root,
                        help="git checkout to describe (default: the project root)")
    args = parser.parse_args(argv)
    if write_build_info(args.repo, args.output):
        print(f"build_info: {describe(args.repo)['version']} -> {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
else:
    # PlatformIO shim: `extra_scripts = pre:scripts/build_info.py` executes this
    # file as an SCons script with Import() in scope. Nothing else in this file
    # depends on PlatformIO.
    try:
        Import("env")  # type: ignore[name-defined]  # noqa: F821
    except NameError:
        pass
    else:
        _pio_env = env  # type: ignore[name-defined]  # noqa: F821
        _pio_root = pathlib.Path(_pio_env.subst("$PROJECT_DIR"))
        _pio_out = pathlib.Path(_pio_env.subst("$PROJECT_INCLUDE_DIR")) / HEADER_NAME
        if write_build_info(_pio_root, _pio_out):
            print(f"build_info: {describe(_pio_root)['version']}")
