"""PlatformIO pre-build script: stamp the firmware with the git revision.

Runs before every build of the environment that lists it under
`extra_scripts` and regenerates include/build_info.hh from the working tree:

    BUILD_GIT_SHA       short commit hash, e.g. "1387909f2a3c"
    BUILD_GIT_DIRTY     1 if tracked files have uncommitted changes
    BUILD_VERSION       `git describe --tags --always --dirty`, e.g.
                        "v1.2-3-g1387909-dirty" (or just the hash with no tags)

The header is only rewritten when its content changes, so an unchanged
revision does not trigger a recompile. It is generated, git-ignored and must
not be edited or committed.
"""
import pathlib
import subprocess

Import("env")  # noqa: F821  (injected by PlatformIO / SCons)

project_dir = env.subst("$PROJECT_DIR")
output = pathlib.Path(env.subst("$PROJECT_INCLUDE_DIR")) / "build_info.hh"


def git(*args):
    try:
        return subprocess.check_output(
            ["git", *args], cwd=project_dir, stderr=subprocess.DEVNULL, text=True
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


sha = git("rev-parse", "--short=12", "HEAD") or "unknown"
dirty = bool(git("status", "--porcelain", "--untracked-files=no"))
version = git("describe", "--tags", "--always", "--dirty") or sha

content = (
    "// Generated by scripts/build_info.py before each firmware build.\n"
    "// Do not edit, do not commit (see .gitignore).\n"
    "#pragma once\n"
    f'#define BUILD_GIT_SHA "{sha}"\n'
    f"#define BUILD_GIT_DIRTY {1 if dirty else 0}\n"
    f'#define BUILD_VERSION "{version}"\n'
)

if not output.exists() or output.read_text() != content:
    output.write_text(content)
    print(f"build_info: {version}")
